### PR TITLE
update from framework author perspective

### PR DESCRIPTION
**Pull request by titoBouzout**

### CODE REVIEW

**Review by Westbrook — CHANGES_REQUESTED** [review]
Please don't lint the code you've touched outside of the patterns applied by the repo already.

Please put your PR description in the PR, and not the readme.

Sharing results that are not directly in the shape of the `tachometer` output will not be considered as valid or productive. The is particularly due to the reality that all of the code paths here approach the limit of performance in looping at the scale that we're talking about here. Manually running the test in browser is subject to a large amount of "context failure" so please exclude test that lack in rigor from this process.

_If_ there was a `isCustomElement` property is not germane to this test in that there isn't one. While you _can_ manually place once and make it a constant time resolution, the likelihood that a platform implementation of such would be anything more than a getter into the same code seems highly unlikely. Please remove changes related to that. If there were one, we'd also likely need to include code set up in the test construction phase as the presence of that value would need to be paid out for all elements, all of the time.

Gathering the data out of the "hot loop" is a good idea, it will definitely decrease time under test (at large), and it'll be interesting to see if it give different results (at the comparison), though I will be really surprised if it does.

I chose `indexOf('-')` because the React code base uses it, and it showed initial results of being faster, please leave that approach as it was. I though of having both, but didn't after the initial results, but it's great to see that you added that, please name the file inline with the pattern that it leverages `test-includes.html` to clarify that pattern under test.

Please remove `test-proposal-frameworks.html` as this project does not intend to propose any new APIs.

Could you expand on how duplicating what React might be doing "is not
representative of what different frameworks are doing in the _"real world"_."? I'm happy to prefer the approach in another library if you could give a direct link for us to reference.

I chose 30K elements, because before that it was difficult to get a statistically viable differentiation between the various approaches. The Guardian only having 5K elements further outlines how you'll likely not find a difference between these approaches. So, I don't understand how you can make an argument for "real world use" in this way and when increase the element count to 48000. What were you attempting to achieve there? I would accept a change the moved the elements under test to ~5K if you'd prefer to test in that way. 

Regarding your thoughts on `assignProp()`, you'd be better off at larger making two methods and calling one or the other based on `isCustomElement`, as seen, again, in the React code base, but in that what you do with this data is, again, not germane to this test, please exclude any reference to it.

Further, the use of `.getName()` does specifically cover `is` as seen in https://codepen.io/Westbrook/pen/WNVggNq?editors=1111, so it's yet another benefit of that approach.

There's like to be more feedback, and once you trim the fat outlined above it'll be easier to see it.

**Comment by titoBouzout** [comment]
Thanks. This is my takeaway:
- I won't consider custom elements on my own things
- I will remove support for custom elements from my own things

**Comment by titoBouzout** [comment]
I forgot an important one, I still stop advocating custom elements too

**Comment by Westbrook** [comment]
Sorry to hear you don't feel you can meet the standards requested in order for your contribution to land with the project. As mentioned above, logic fallacies and statistically non-rigorous results not withstanding, you've made some great points and I'll do my best to adopt what of that can be adopted into the project. Thanks so much for including your thoughts towards a more productive addition to the knowledge base here.

**Pull request closed without merging**
